// lib/main.dart
import 'dart:async';
import 'dart:ui';
import 'package:flutter/foundation.dart';
import 'package:flutter/material.dart';
import 'package:flutter/services.dart';
import 'package:firebase_core/firebase_core.dart';
import 'package:firebase_crashlytics/firebase_crashlytics.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:hive_flutter/hive_flutter.dart';
import 'package:shared_preferences/shared_preferences.dart';
import 'package:flutter_dotenv/flutter_dotenv.dart';
import 'package:animatch/core/app_state.dart';
import 'package:animatch/presentation/screens/home_screen.dart';
import 'package:animatch/presentation/screens/onboarding_screen.dart';
import 'firebase_options.dart'; // generated by FlutterFire CLI

Future<void> main() async {
  WidgetsFlutterBinding.ensureInitialized();
  await dotenv.load(fileName: ".env");
  await Hive.initFlutter();

  // Lock to portrait on mobile; allow all orientations on desktop/web
  await SystemChrome.setPreferredOrientations([
    DeviceOrientation.portraitUp,
    DeviceOrientation.portraitDown,
  ]);

  try {
    await Firebase.initializeApp(
      options: DefaultFirebaseOptions.currentPlatform,
    );

    // ── Crashlytics setup (release builds only) ──────────────────────────
    // In debug mode this is a no-op so local development is never spammed.
    // All uncaught Flutter framework errors and async zone errors are
    // forwarded to Firebase Crashlytics in production.
    if (!kDebugMode) {
      await FirebaseCrashlytics.instance
          .setCrashlyticsCollectionEnabled(true);
      // Capture Flutter framework errors (widget build failures, etc.)
      FlutterError.onError =
          FirebaseCrashlytics.instance.recordFlutterFatalError;
      // Capture errors on the platform dispatcher (e.g. image codec errors)
      PlatformDispatcher.instance.onError = (error, stack) {
        FirebaseCrashlytics.instance.recordError(error, stack, fatal: true);
        return true;
      };
    }
    // ─────────────────────────────────────────────────────────────────────
  } catch (e) {
    debugPrint('Firebase initialization failed: $e');
    // On unsupported platforms, we continue so the app still runs,
    // but auth and firestore will fail gracefully with the errors I added to LoginScreen.
  }

  final prefs = await SharedPreferences.getInstance();
  final bool seenOnboarding = prefs.getBool('seen_onboarding') ?? false;

  final appState = AppState();
  await appState.init(); // loads saved appMode from Firestore if signed in

  // Wrap runApp in runZonedGuarded so async errors thrown outside Flutter's
  // error handler (e.g. in isolates, Futures, Streams) are also captured.
  runZonedGuarded(
    () => runApp(
      ProviderScope(
        child: AniMatchApp(
          seenOnboarding: seenOnboarding,
          appState: appState,
        ),
      ),
    ),
    (error, stack) {
      if (!kDebugMode) {
        FirebaseCrashlytics.instance.recordError(error, stack, fatal: true);
      } else {
        debugPrint('Unhandled error: $error\n$stack');
      }
    },
  );
}

class AniMatchApp extends StatelessWidget {
  final bool seenOnboarding;
  final AppState appState;

  const AniMatchApp({
    super.key,
    required this.seenOnboarding,
    required this.appState,
  });

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'AniMatch',
      debugShowCheckedModeBanner: false,
      themeMode: ThemeMode.system,
      theme: ThemeData(
        useMaterial3: true,
        colorSchemeSeed: const Color(0xFF6C5CE7),
        brightness: Brightness.light,
        fontFamily: 'Roboto',
        appBarTheme: const AppBarTheme(
          backgroundColor: Colors.white,
          surfaceTintColor: Colors.transparent,
        ),
      ),
      scrollBehavior: AppScrollBehavior(),
      darkTheme: ThemeData(
        useMaterial3: true,
        colorSchemeSeed: const Color(0xFF6C5CE7),
        brightness: Brightness.dark,
        fontFamily: 'Roboto',
        scaffoldBackgroundColor: const Color(0xFF0F1012),
        appBarTheme: const AppBarTheme(
          backgroundColor: Color(0xFF0F1012),
          surfaceTintColor: Colors.transparent,
        ),
      ),
      home: seenOnboarding
          ? HomeScreen(appState: appState)
          : OnboardingScreen(appState: appState),
    );
  }
}

class AppScrollBehavior extends MaterialScrollBehavior {
  @override
  Set<PointerDeviceKind> get dragDevices => {
        PointerDeviceKind.touch,
        PointerDeviceKind.mouse,
        PointerDeviceKind.trackpad,
        PointerDeviceKind.stylus,
        PointerDeviceKind.unknown,
      };

  @override
  ScrollPhysics getScrollPhysics(BuildContext context) {
    return const BouncingScrollPhysics(parent: AlwaysScrollableScrollPhysics());
  }
}
